ST = stack.c
QU = queue.c

all : 1 2 3 4 5 6

1 :
	gcc $(ST) q01.c
	./a.out
	rm a.out

2 :
	gcc $(ST) q02.c
	./a.out
	rm a.out

3 :
	gcc $(QU) q03.c
	./a.out
	rm a.out

4 :
	gcc $(QU) q04-05.c
	./a.out
	rm a.out

5 :
	gcc $(QU) q04-05.c
	./a.out
	rm a.out

6 :
	gcc $(QU) q06.c
	./a.out
	rm a.out
