all : 1 2 3 4 5 6 7 8 9

1 :
	gcc q01.c
	./a.out
	rm a.out

2 :
	gcc q02.c
	./a.out
	rm a.out

3 :
	gcc q03.c
	./a.out
	rm a.out

4 :
	gcc q04.c
	./a.out
	rm a.out

5 :
	gcc q05.c
	./a.out
	rm a.out

6 :
	gcc q06.c
	./a.out
	rm a.out

7 :
	gcc q07.c
	./a.out
	rm a.out

8 :
	gcc q08.c
	./a.out
	rm a.out

9 :
	gcc q09.c
	./a.out
	rm a.out